slug: Creating an Enabling Environment for Upscaling Ecosystem-based Adaptation
citation: >-
  TMG Research: Creating an Enabling Environment for Upscaling Ecosystem based Adaptation (2019).
  Video.
category: video
url: "https://www.youtube.com/watch?v=b1I0A_DgU6c&list=PLjvvJHyZ19uCC0tFmjfPB_J5sFYoAs7uI&index=2"
year: 2019
languageNote: English and Spanish
sortOrder: 3
