slug: Creating an Enabling Environment for Upscaling Ecosystem-based Adaptation
citation: >-
  TMG Research: Creating an Enabling Environment for Upscaling Ecosystem based Adaptation (2019).
  Video.
category: video
year: 2019
languageNote: English and Spanish
sortOrder: 3
